# Use container-based infrastructure
sudo: false

language: scala

jdk: oraclejdk8

scala:
   - 2.10.4
   - 2.12.6

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

